# Generated by Django 2.0.6 on 2018-06-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
