# Generated by Django 2.0.6 on 2018-06-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_tracker', '0002_round_round_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infectioncard',
            name='special',
        ),
        migrations.AddField(
            model_name='infectioncard',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CardSpecial',
        ),
    ]
