# Generated by Django 2.0.6 on 2018-06-24 20:20
from datetime import date

from django.db import migrations


def populate_game_on_rounds(apps, schema_editor):
    Round = apps.get_model('infection_tracker', 'Round')
    Game = apps.get_model('infection_tracker', 'Game')

    game = Game.objects.create(date=date.today())
    for round in Round.objects.all():
        round.game = game
        round.save()


class Migration(migrations.Migration):

    dependencies = [
        ('infection_tracker', '0004_auto_20180624_2018'),
    ]

    operations = [
        migrations.RunPython(populate_game_on_rounds)
    ]
