# Generated by Django 2.0.6 on 2018-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_tracker', '0006_game_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.NullBooleanField(),
        ),
    ]
