# Generated by Django 2.0.6 on 2018-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infection_tracker', '0007_game_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_cities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
