# Generated by Django 3.1.2 on 2020-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo for afffiliation'),
        ),
    ]
