# Generated by Django 3.1.2 on 2020-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0002_auto_20201031_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(choices=[('na', 'North America'), ('sa', 'South America'), ('eu', 'Europe'), ('af', 'Africa'), ('as', 'Asia'), ('pr', 'Pacific Rim')], default='eu', max_length=20),
        ),
    ]
