# Generated by Django 3.1.2 on 2020-10-31 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0003_city_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(choices=[('na', 'North America'), ('sa', 'South America'), ('eu', 'Europe'), ('af', 'Africa'), ('as', 'Asia'), ('pr', 'Pacific Rim')], default='as', max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='region_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='game_tracker.region'),
        ),
    ]
