# Generated by Django 3.1.2 on 2020-10-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0005_auto_20201031_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='region_link',
            new_name='region',
        ),
    ]
